export const GET_CARD_STEP = "GET_CARD_STEP";
export const APPLICATION_ITEMS = "APPLICATION_ITEMS";
export const APPLICATION_STEP = "APPLICATION_STEP";
export const CURRENT_APPLICATION_ID = "CURRENT_APPLICATION_ID";
